-- MySQL Script generated by MySQL Workbench
-- Thu Oct 12 20:33:41 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';
ALTER TABLE `home`.`accounting_check` CONVERT TO CHARACTER SET utf8 COLLATE utf8_general_ci;
ALTER TABLE `home`.`change_count` CONVERT TO CHARACTER SET utf8 COLLATE utf8_general_ci;
ALTER TABLE `home`.`consumer` CONVERT TO CHARACTER SET utf8 COLLATE utf8_general_ci;
ALTER TABLE `home`.`counter` CONVERT TO CHARACTER SET utf8 COLLATE utf8_general_ci;
ALTER TABLE `home`.`dimension` CONVERT TO CHARACTER SET utf8 COLLATE utf8_general_ci;
ALTER TABLE `home`.`object` CONVERT TO CHARACTER SET utf8 COLLATE utf8_general_ci;
ALTER TABLE `home`.`plombs` CONVERT TO CHARACTER SET utf8 COLLATE utf8_general_ci;
ALTER TABLE `home`.`transfor_cur` CONVERT TO CHARACTER SET utf8 COLLATE utf8_general_ci;
ALTER TABLE `home`.`transfor_vol` CONVERT TO CHARACTER SET utf8 COLLATE utf8_general_ci;
ALTER TABLE `home`.`user` CONVERT TO CHARACTER SET utf8 COLLATE utf8_general_ci;
ALTER TABLE `home`.`Type_date` CONVERT TO CHARACTER SET utf8 COLLATE utf8_general_ci;
ALTER TABLE `home`.`Date_list` CONVERT TO CHARACTER SET utf8 COLLATE utf8_general_ci;
ALTER TABLE `home`.`All_dates` CONVERT TO CHARACTER SET utf8 COLLATE utf8_general_ci;
-- -----------------------------------------------------
-- Schema home
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema home
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `home` DEFAULT CHARACTER SET utf8 ;
USE `home` ;

-- -----------------------------------------------------
-- Table `home`.`Consumer`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `home`.`Consumer` (
  `id_consumer` INT NOT NULL,
  `Name_consumer` VARCHAR(45) NULL,
  `Phone_consumer` VARCHAR(45) NULL,
  `Personal_account` VARCHAR(45) NULL,
  `Face` VARCHAR(45) NULL,
  PRIMARY KEY (`id_consumer`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `home`.`Object`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `home`.`Object` (
  `id_object` INT NOT NULL,
  `Owner_FIO` VARCHAR(45) NULL,
  `Renter_FIO` VARCHAR(45) NULL,
  `Name_object` VARCHAR(45) NULL,
  `Mailing_address` VARCHAR(45) NULL,
  `Phone_object` VARCHAR(45) NULL,
  `Source_of_power` VARCHAR(45) NULL,
  `Voltage_class` VARCHAR(45) NULL,
  `Date_instrumental_check` VARCHAR(45) NULL,
  `Obj_Cons_id` INT NOT NULL,
  PRIMARY KEY (`id_object`, `Obj_Cons_id`),
  INDEX `fk_Объект_Потребитель_idx` (`Obj_Cons_id` ASC),
  CONSTRAINT `fk_Объект_Потребитель`
    FOREIGN KEY (`Obj_Cons_id`)
    REFERENCES `home`.`Consumer` (`id_consumer`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `home`.`Transfor_vol`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `home`.`Transfor_vol` (
  `id_tr_vol` INT NOT NULL,
  `Type_tr_vol` VARCHAR(45) NULL,
  `Mark_tr_vol` VARCHAR(45) NULL,
  `Denomin_tr_vol` VARCHAR(45) NULL,
  `Plomb_tr_vol` VARCHAR(45) NULL,
  `Object_ id_object` INT NOT NULL,
  `Object_Obj_Cons_id` INT NOT NULL,
  PRIMARY KEY (`id_tr_vol`),
  INDEX `fk_Transfor_vol_Object1_idx` (`Object_ id_object` ASC, `Object_Obj_Cons_id` ASC),
  CONSTRAINT `fk_Transfor_vol_Object1`
    FOREIGN KEY (`Object_ id_object` , `Object_Obj_Cons_id`)
    REFERENCES `home`.`Object` (`id_object` , `Obj_Cons_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `home`.`Counter`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `home`.`Counter` (
  `id_count` INT NOT NULL,
  `Type_count` VARCHAR(45) NULL,
  `Mark_count` VARCHAR(45) NULL,
  `Number_count` VARCHAR(45) NULL,
  `Year_release_count` VARCHAR(45) NULL,
  `Class_accur_count` VARCHAR(45) NULL,
  `Kol_plomb_gospr` VARCHAR(45) NULL,
  `Kol_holog_stick` VARCHAR(45) NULL,
  `Plomb_netw_org` VARCHAR(45) NULL,
  `Antimag_plomb` VARCHAR(45) NULL,
  `Plomb_shu` VARCHAR(45) NULL,
  `Other_places_count` VARCHAR(45) NULL,
  `Obj_id_count` INT NOT NULL,
  `Obj_Cons_id_count` INT NOT NULL,
  PRIMARY KEY (`id_count`, `Obj_id_count`, `Obj_Cons_id_count`),
  INDEX `fk_Счетчик_Объект1_idx` (`Obj_id_count` ASC, `Obj_Cons_id_count` ASC),
  CONSTRAINT `fk_Счетчик_Объект1`
    FOREIGN KEY (`Obj_id_count` , `Obj_Cons_id_count`)
    REFERENCES `home`.`Object` (`id_object` , `Obj_Cons_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `home`.`Transfor_cur`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `home`.`Transfor_cur` (
  `id_tr_cur` INT NOT NULL,
  `Type_tr_cur` VARCHAR(45) NULL,
  `Mark_tr_cur` VARCHAR(45) NULL,
  `Denomin_tr_cur` VARCHAR(45) NULL,
  `Year_release_tr_cur` VARCHAR(45) NULL,
  `Num_tr_cur_fa` VARCHAR(45) NULL,
  `Num_tr_cur_fb` VARCHAR(45) NULL,
  `Num_tr_cur_fc` VARCHAR(45) NULL,
  `Phase_tr_cur` VARCHAR(45) NULL,
  PRIMARY KEY (`id_tr_cur`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `home`.`Plombs`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `home`.`Plombs` (
  `id_plomb` INT NOT NULL,
  `L1` VARCHAR(45) NULL,
  `L2` VARCHAR(45) NULL,
  `I1` VARCHAR(45) NULL,
  `I2` VARCHAR(45) NULL,
  `Other_places_plomb` VARCHAR(45) NULL,
  `Tr_cur_id_plomb` INT NOT NULL,
  PRIMARY KEY (`id_plomb`, `Tr_cur_id_plomb`),
  INDEX `fk_Пломбы_Трансформатор тока1_idx` (`Tr_cur_id_plomb` ASC),
  CONSTRAINT `fk_Пломбы_Трансформатор тока1`
    FOREIGN KEY (`Tr_cur_id_plomb`)
    REFERENCES `home`.`Transfor_cur` (`id_tr_cur`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `home`.`Dimension`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `home`.`Dimension` (
  `id_dimen` INT NOT NULL,
  `Date_dimen` VARCHAR(45) NULL,
  `Alter_phase` VARCHAR(45) NULL,
  `Load_fa` VARCHAR(45) NULL,
  `Load_fb` VARCHAR(45) NULL,
  `Load_fc` VARCHAR(45) NULL,
  `Cos_fi` VARCHAR(45) NULL,
  `Kol_turn_disk` VARCHAR(45) NULL,
  `Power_consum` VARCHAR(45) NULL,
  `Obj_id_dimen` INT NOT NULL,
  `Obj_Cons_id_dimen` INT NOT NULL,
  PRIMARY KEY (`id_dimen`),
  INDEX `fk_Данные об измерениях_Объект1_idx` (`Obj_id_dimen` ASC, `Obj_Cons_id_dimen` ASC),
  CONSTRAINT `fk_Данные об измерениях_Объект1`
    FOREIGN KEY (`Obj_id_dimen` , `Obj_Cons_id_dimen`)
    REFERENCES `home`.`Object` (`id_object` , `Obj_Cons_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `home`.`Accounting_check`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `home`.`Accounting_check` (
  `id_check` INT NOT NULL,
  `Date_check` VARCHAR(45) NULL,
  `Type_verif` VARCHAR(45) NULL,
  `Conclusion_ac` VARCHAR(45) NULL,
  `Notes_ac` VARCHAR(45) NULL,
  PRIMARY KEY (`id_check`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `home`.`Change_count`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `home`.`Change_count` (
  `id_change` INT NOT NULL,
  `Date_change` VARCHAR(45) NULL,
  `Cause_change` VARCHAR(45) NULL,
  `FIO_change` VARCHAR(45) NULL,
  `Nomber_old` VARCHAR(45) NOT NULL,
  `Nomber_new` VARCHAR(45) NOT NULL,
  `Counter_id_count` INT NOT NULL,
  `Counter_Obj_id_count` INT NOT NULL,
  `Counter_Obj_Cons_id_count` INT NOT NULL,
  PRIMARY KEY (`id_change`),
  INDEX `fk_Change_count_Counter1_idx` (`Counter_id_count` ASC, `Counter_Obj_id_count` ASC, `Counter_Obj_Cons_id_count` ASC),
  CONSTRAINT `fk_Change_count_Counter1`
    FOREIGN KEY (`Counter_id_count` , `Counter_Obj_id_count` , `Counter_Obj_Cons_id_count`)
    REFERENCES `home`.`Counter` (`id_count` , `Obj_id_count` , `Obj_Cons_id_count`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `home`.`Type_date`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `home`.`Type_date` (
  `idType` INT NULL,
  `Type` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idType`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `home`.`Date_list`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `home`.`Date_list` (
  `idDate` INT NOT NULL,
  `Date` DATE NOT NULL,
  `Type_date_idType` INT NOT NULL,
  PRIMARY KEY (`idDate`, `Type_date_idType`),
  INDEX `fk_Date_list_Type_date1_idx` (`Type_date_idType` ASC),
  CONSTRAINT `fk_Date_list_Type_date1`
    FOREIGN KEY (`Type_date_idType`)
    REFERENCES `home`.`Type_date` (`idType`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `home`.`All_dates`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `home`.`All_dates` (
  `Date_list_idDate` INT NOT NULL,
  `Counter_id_count` INT NOT NULL,
  `Transfor_vol_id` INT NOT NULL,
  `Transfor_cur_id` INT NOT NULL,
  `Conclusio` VARCHAR(45) NULL,
  `Notes` VARCHAR(45) NULL,
  PRIMARY KEY (`Date_list_idDate`),
  INDEX `fk_Date_list_has_Counter_Counter1_idx` (`Counter_id_count` ASC),
  INDEX `fk_Date_list_has_Counter_Date_list1_idx` (`Date_list_idDate` ASC),
  INDEX `fk_Date_list_has_Counter_Transfor_vol1_idx` (`Transfor_vol_id` ASC),
  INDEX `fk_Date_list_has_Counter_Transfor_cur1_idx` (`Transfor_cur_id` ASC),
  CONSTRAINT `fk_Date_list_has_Counter_Date_list1`
    FOREIGN KEY (`Date_list_idDate`)
    REFERENCES `home`.`Date_list` (`idDate`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Date_list_has_Counter_Counter1`
    FOREIGN KEY (`Counter_id_count`)
    REFERENCES `home`.`Counter` (`id_count`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Date_list_has_Counter_Transfor_vol1`
    FOREIGN KEY (`Transfor_vol_id`)
    REFERENCES `home`.`Transfor_vol` (`id_tr_vol`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Date_list_has_Counter_Transfor_cur1`
    FOREIGN KEY (`Transfor_cur_id`)
    REFERENCES `home`.`Transfor_cur` (`id_tr_cur`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
